### ISSUE TITLE
charter: goal and non goal inconsistency

### ISSUE THREAD

**Issue by rootfs** [cncf/wg-env-sustainability#7]
The goals and non goals are inconsistently stated in the charter. It creates more confusion than guidance. For instance, the goals below state to use tools and projects for their intended objectives, while such activities are victims of non goals at the same time, i.e. creating or recommending projects or tools.

```
Ecosystem: Foster and grow the ecosystem of environmental sustainability projects, users and maintainers
Best Practices: Define procedures to improve environmental sustainability factors, develop benchmarks for the quantification of energy consumption of software, develop techniques to manage software such that the overall energy consumption and associated carbon is reduced.
Guidance: Support open source tools that improve environmental sustainability factors and emphasize environmental sustainability concerns
```

**Comment by mkorbi** [comment]
I think this doesn't conflict.
As WG we support tool A, maybe in guidance of setting up an OSS project, or through research insights, doesn't matter.
What we don't do as WG is to say tool A is our absolute favorite, but also not tool B or C. As WG we respect all tools the same way.
However, I as a "private" person can like a tool C more and would recommend this in case asked.

**Comment by rootfs** [comment]
> As WG we support tool A, maybe in guidance of setting up an OSS project, or through research insights, doesn't matter.
The unstated assumption is that there are such tools around and they serve the purpose of our work. In many cases, you may find that's not the case and new tools have to be created. 

> What we don't do as WG is to say tool A is our absolute favorite, but also not tool B or C. As WG we respect all tools the same way.
None of the CNCF projects I have been working on has `absolute favorite`, but none of them has explicitly spelled non-goals of not creating or recommending tools. 

Neutrality and exclusivity are two different positions. CNCF is designed to be inclusive to innovations. More deliberation is needed. Let's bring this discussion to the community meeting.

**Comment by mkorbi** [comment]
As discussed on our Wednesday 15th of June 2022 meeting. We are currently in the state of a WG, the brought-up topics in the meeting matching the discussion here are currently not in focus.
