### ISSUE TITLE
[charter]Other Related Groups: mention other sustainability oriented communities

### ISSUE THREAD

**Issue by rootfs** [cncf/wg-env-sustainability#8]
- [OS-Climate](https://os-climate.org/), another group under LF, uses data and technologies to accelerate investment with sustainable impacts
- Open Compute Project. Thought it is mostly about systems, some projects such as [heat reuse](https://www.opencompute.org/projects/heat-reuse-incubation), can help software systems to build a better heuristics, e.g. through OpenTelemetry.

**Comment by wojtekidd** [comment]
[Green Software Foundation](https://greensoftware.foundation/)

**Comment by ng-druid** [comment]
[Roll the Cloud](https://rollthecloud.com/)

**Comment by mkorbi** [comment]
Under discussion https://github.com/cncf/wg-env-sustainability/discussions/16
